
export interface Country {
  name: string;
  code: string; // ISO 3166-1 alpha-2 code
}

// Shortened list for demonstration. In a real app, use a comprehensive list.
export const countries: Country[] = [
  { name: 'Afeganistão', code: 'AF' },
  { name: 'África do Sul', code: 'ZA' },
  { name: 'Albânia', code: 'AL' },
  { name: 'Alemanha', code: 'DE' },
  { name: 'Andorra', code: 'AD' },
  { name: 'Angola', code: 'AO' },
  { name: 'Arábia Saudita', code: 'SA' },
  { name: 'Argélia', code: 'DZ' },
  { name: 'Argentina', code: 'AR' },
  { name: 'Austrália', code: 'AU' },
  { name: 'Áustria', code: 'AT' },
  { name: 'Bangladesh', code: 'BD' },
  { name: 'Bélgica', code: 'BE' },
  { name: 'Bolívia', code: 'BO' },
  { name: 'Brasil', code: 'BR' },
  { name: 'Canadá', code: 'CA' },
  { name: 'Chile', code: 'CL' },
  { name: 'China', code: 'CN' },
  { name: 'Colômbia', code: 'CO' },
  { name: 'Coreia do Sul', code: 'KR' },
  { name: 'Costa Rica', code: 'CR' },
  { name: 'Croácia', code: 'HR' },
  { name: 'Dinamarca', code: 'DK' },
  { name: 'Egito', code: 'EG' },
  { name: 'Emirados Árabes Unidos', code: 'AE' },
  { name: 'Equador', code: 'EC' },
  { name: 'Espanha', code: 'ES' },
  { name: 'Estados Unidos', code: 'US' },
  { name: 'Filipinas', code: 'PH' },
  { name: 'Finlândia', code: 'FI' },
  { name: 'França', code: 'FR' },
  { name: 'Grécia', code: 'GR' },
  { name: 'Holanda', code: 'NL' },
  { name: 'Índia', code: 'IN' },
  { name: 'Indonésia', code: 'ID' },
  { name: 'Irlanda', code: 'IE' },
  { name: 'Itália', code: 'IT' },
  { name: 'Japão', code: 'JP' },
  { name: 'Luxemburgo', code: 'LU' },
  { name: 'Malásia', code: 'MY' },
  { name: 'Marrocos', code: 'MA' },
  { name: 'México', code: 'MX' },
  { name: 'Moçambique', code: 'MZ' },
  { name: 'Nigéria', code: 'NG' },
  { name: 'Noruega', code: 'NO' },
  { name: 'Nova Zelândia', code: 'NZ' },
  { name: 'Panamá', code: 'PA' },
  { name: 'Paraguai', code: 'PY' },
  { name: 'Peru', code: 'PE' },
  { name: 'Polônia', code: 'PL' },
  { name: 'Portugal', code: 'PT' },
  { name: 'Reino Unido', code: 'GB' },
  { name: 'República Tcheca', code: 'CZ' },
  { name: 'Rússia', code: 'RU' },
  { name: 'Singapura', code: 'SG' },
  { name: 'Suécia', code: 'SE' },
  { name: 'Suíça', code: 'CH' },
  { name: 'Tailândia', code: 'TH' },
  { name: 'Turquia', code: 'TR' },
  { name: 'Uruguai', code: 'UY' },
  { name: 'Venezuela', code: 'VE' },
  // Add more countries as needed or use a comprehensive library
];
